import PDFDocument from 'pdfkit';
import QRCode from 'qrcode';
import { formatDate } from '@/lib/utils';

type CertificatePdfInput = {
  id: string;
  certificate_number: string;
  workspace_name: string;
  ai_system_name: string;
  model_name: string;
  ai_output_hash: string;
  human_reviewer_name: string;
  human_reviewer_email: string;
  human_reviewer_role: string;
  decision: string;
  decision_notes: string;
  risk_flags: string[];
  issued_at: string;
  payload_hash: string;
  certificate_hash: string;
  signature: string;
  verification_url: string;
};

export async function generateCertificatePdf(input: CertificatePdfInput) {
  const qr = await QRCode.toDataURL(input.verification_url, { margin: 1, width: 160 });

  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 48 });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk) => chunks.push(Buffer.from(chunk)));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.rect(0, 0, doc.page.width, doc.page.height).fill('#05070D');
    doc
      .fillColor('#22D3EE')
      .fontSize(12)
      .text('SENTINELUM OVERSIGHT CERTIFICATE', 48, 48, { characterSpacing: 1.6 });
    doc.fillColor('#F8FAFC').fontSize(28).text(input.certificate_number, 48, 80);
    doc
      .fillColor('#94A3B8')
      .fontSize(11)
      .text('Cryptographic evidence that a human reviewer stayed in control of a critical AI decision.', 48, 118, {
        width: 360
      });

    doc.image(qr, 438, 48, { width: 108 });

    const rows: Array<[string, string]> = [
      ['Workspace', input.workspace_name],
      ['Certificate ID', input.id],
      ['Issued UTC', formatDate(input.issued_at)],
      ['AI system', input.ai_system_name],
      ['Model', input.model_name],
      ['Human reviewer', `${input.human_reviewer_name} <${input.human_reviewer_email}>`],
      ['Reviewer role', input.human_reviewer_role],
      ['Decision', input.decision],
      ['Risk flags', input.risk_flags.join(', ') || 'None recorded']
    ];

    let y = 178;
    rows.forEach(([label, value]) => {
      doc.fillColor('#64748B').fontSize(9).text(label.toUpperCase(), 48, y);
      doc.fillColor('#F8FAFC').fontSize(12).text(value, 190, y, { width: 330 });
      y += 30;
    });

    doc.fillColor('#64748B').fontSize(9).text('DECISION NOTES', 48, y + 10);
    doc.fillColor('#F8FAFC').fontSize(11).text(input.decision_notes, 48, y + 28, { width: 498 });

    y += 105;
    const hashes: Array<[string, string]> = [
      ['AI output hash', input.ai_output_hash],
      ['Payload hash', input.payload_hash],
      ['Certificate hash', input.certificate_hash],
      ['Signature', input.signature],
      ['Verification URL', input.verification_url]
    ];

    doc
      .roundedRect(48, y, 498, 220, 8)
      .strokeColor('#1F3B52')
      .lineWidth(1)
      .stroke();

    let hashY = y + 22;
    hashes.forEach(([label, value]) => {
      doc.fillColor('#22D3EE').fontSize(8).text(label.toUpperCase(), 70, hashY);
      doc
        .fillColor('#DCEBFF')
        .font('Courier')
        .fontSize(8)
        .text(value, 70, hashY + 13, { width: 455 });
      doc.font('Helvetica');
      hashY += 40;
    });

    doc
      .fillColor('#64748B')
      .fontSize(8)
      .text('Generated by Sentinelum. Verification depends on the stored payload hash and HMAC signature.', 48, 800);

    doc.end();
  });
}
