import { env } from '@/lib/env';

export const secrets = {
  CERTIFICATE_SIGNING_SECRET: env.CERTIFICATE_SIGNING_SECRET,
  API_KEY_HASH_SECRET: env.API_KEY_HASH_SECRET,
  WEBHOOK_SIGNING_SECRET: env.WEBHOOK_SIGNING_SECRET,
  ENCRYPTION_KEY: env.ENCRYPTION_KEY
};
